import pandas as pd

# Prepare contact data
data = [
    ["Jane Scolastika", "Wipro", "jane.scolastika@wipro.com"],
    [None, "Heritage Foods", "recruitment@heritagefoods.co.in"],
    ["Sumat", "Cognizant", "sumat.cts@gmail.com"],
    ["Tara Jendra", "DST Worldwide Services", "tarajendra@dstworldwideservices.com"],
    [None, "Genpact", "Careers.analytics@genpact.com"],
    ["A. Ranjan", "FactSet", "aranjan@factset.com"],
    ["Minu Mavoori", "Broadridge", "minu.mavoori@broadridge.com"],
    ["Pal Reddy", "Deloitte", "palreddy@deloitte.com"],
    ["V. Baldev", "Deloitte", "vbaldev@deloitte.com"],
    [None, "HSBC", "recruitmentsdpi@hsbc.co.in"],
    [None, "Invesco", "bridgers_headers@eth.net"],
    ["Swati Singh", "United Health Group", "swati_singh@uhg.com"],
    ["Chandrappa B", "LIC", "chandrappa.b@licindia.com"],
    ["Sriram K", "ALP Consulting", "sriram.k@alpconsulting.in"],
    ["Saptavaani", "ALP Consulting", "saptavaani@alpconsulting.in"],
    ["Rohini S", "ALP Consultants", "rohini.s@alpconsultants.com"],
    [None, "Mahindra Satyam BPO", "recruitment@mahindrasatyambpo.com"],
    ["Rama Y", "Sew Infrastructure", "rama.y@sewinfrastructure.com"],
    [None, "My Home Constructions", "mhchrteam@myhomeconstructions.com"],
    ["Dilip Sharma", "BL Kashyap", "dilipsharma@blkashyap.com"],
    [None, "BL Kashyap", "hrdelhi@blkashyap.com"],
    [None, "Aparna Constructions", "careers@aparnaconstructions.com"],
    [None, "SHRIRAM AP", "shriramaphrd@schits.com"],
    [None, "Genpact", "careers.hyderabad@genpact.com"],
    ["Raees R", "Deloitte", "rraees@deloitte.com"],
    [None, "Facebook", "facebook-recruiting@fb.com"],
    [None, "Career Logic", "hr@careerlogic.in"],
    ["Avanthi G", "PeopleStrong", "Avanthi.g@peoplestrong.com"],
    ["Ashwini", "Career Logic", "ashwini@careerlogic.in"],
    ["Nazia", "Focus Softnet", "nazia@focussoftnet.com"],
    [None, "Gateway Hyd", "jobs@gatewayhyd.com"],
    ["Siva R", "ALP Consulting", "siva.r@alpconsulting.in"],
    ["Neha G", "ALP Consulting", "neha.g@alpconsulting.in"],
    ["Sricha", "Magna", "sricha@magna.in"],
    [None, "Templeton", "careersindia@templeton.com"],
    ["Daddu", "FactSet", "daddu@factset.com"],
    ["Kalpana", "Karvy / Urooj Solutions", "kalpanahr@karvy.com / kalpana.urooj1@gmail.com"],
    ["Ali Hussain", None, "alihussainmba@yahoo.com"],
    ["Harshitha Mecha", "Manpower", "harshitha.mecha@manpower.co.in"],
    ["A. Vivek", "Manpower", "a.vivek@manpower.co.in"],
    ["Yamini", "Phare", "yamini@phare.co.in"],
    ["Kiran", "Manpower", "kiran.manpower@outlook.com"],
    [None, "FactSet", "recruiting_india@factset.com"],
    ["N. Pilli", "Deloitte", "npilli@deloitte.com"],
    ["Nandu (Disis)", None, "disisnandu@gmail.com"],
    ["Jyothica", "Amazon", "jyothica@amazon.com"],
    [None, "Capital IQ", "JRA_Careers@capitaliq.co.in"],
    [None, "DST Worldwide Services", "indiacareers@dstworldwideservices.com"],
    ["Seetal Keshri", "Wealthfolio", "seetal.keshri@wealthfolio.in"],
    ["Akash Shivnarayan", "Accenture", "akash.shivnarayan@accenture.com"],
    ["Meghana S", "Career Routes", "meghana.s@careeroutes.com"],
    [None, "Shore Group", "hr@shoregrp.com"],
    ["Nihar G", "Randstad", "nihar.g@randstad.in"],
    ["Samyuktha Vedanthan", "Randstad", "samyuktha.vedanthan@randstad.in"],
    ["Sesha Sayana", "Ma Foi", "sesha.sayana@mafoi.com"],
    [None, "Randstad", "upendra.randstad@gmai"],
    ["Nihar D", "ALP Consulting", "nihar.d@alpconsulting.in"],
    [None, "Urooj Solutions", "asha.urooj1@gmail.com"],
    ["Diana", "Rainboz Solutions", "Dianarainboz@gmail.com"],
    [None, "Rainboz Solutions", "voice.recruiters@gmail.com"],
    ["Joseph Akhil", "Hucon Solutions", "josephakhil002@gmail.com"],
    ["Sameera", "Stryde Consulting", "sameera@strydeconsulting.com"],
    ["Pravalika A", "Flatmind IT Solutions", "pravalika.a@flatmindtech.com"],
    ["Tirukalla Christina", "Serco", "tirukalla.christina@serco.com"],
    ["Sagar", "Genesso Consulting", "sagar@genessoconsultants.com"],
    ["Vijay", "Futurz Consultancy", "vijay@futurzconsultancyservices.com"],
    ["Farah", "Futurz Consultancy", "farah@futurzconsultancyservices.com"],
    [None, "Career Mentors", "Clients@Careermentors.in"],
    ["Sabitha", "HR Capital Services", "sabitha@hrcapitalservices.com"],
    [None, "Career Logic Staffing", "careerlogicstaffing@in.com"],
    ["Bishakha Saha", "Manpower Consultancy", "bishakha.saha@manpower.co.in"],
    [None, "Fair Links Consultancy", "hr@fairlinksindia.com"],
    ["B. Swamy", "2COMS", "b.swamy@2coms.com"],
    [None, "Jobs and Career Consultant", "voice.bpo2@gmail.com"],
    ["Priyanka Behl", "Inno HR Solution", "priyankabehl88@yahoo.com"],
    [None, "Mango Staffing Solutions", "mangostaffingsolutions@gmail.com"],
    [None, "Covidien (Healthcare)", "RDjobs@covidien.in"],
    ["Kamesh Chavali", "Dupont", "kamesh.chavali@ind.dupont.com"],
    ["Priya Gundeboina", "Mahindra Satyam", "priya.gundeboina@mahindrasatyambsg.com"],
    [None, "Mahindra Satyam", "recruitment@mahindrasatyambsg.com"],
    ["Vishwa M", "India Infoline", "vishwa.m@indiainfoline.com"],
    ["Afreen Sultana", "Adaptive Payments India", "afreen_sultana@adaptivepayments.com"],
    [None, "Prism Networks Pvt Ltd", "hr@eventtracker.com"]
]

# Create DataFrame
df_contacts = pd.DataFrame(data, columns=["Name", "Company", "Email"])
df_contacts["Status"] = ""

# Save to Excel
excel_path = r"C:\New folder\contacts_formatted.xlsx"
df_contacts.to_excel(excel_path, index=False)

excel_path

